### ISSUE TITLE
How to handle pauses between words

### ISSUE THREAD

**Issue by TravisBumgarner** [TravisBumgarner/strangerer_things#4]

**Comment by tenth10th** [comment]
I think just having a pause (during which no lights are illuminated) could work, especially if the duration between letters is short.

Having individual letters fade in and then out (via brightness) would also help make repeated letters more comprehensible.

If we can't do brightness, having the whole board stay dark for a second or two (or have the whole board randomly "blink" once) could also be used to separate words more clearly.

(There isn't a great reference for this in the show, since IIRC it only displayed single word "answers", one letter at a time, to each question Joyce was asking it...)

**Comment by TravisBumgarner** [comment]
Added some constants at the beginning of the doc to toggle this.
